name: build
on: [pull_request]
jobs:
  vercel-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable && corepack prepare pnpm@9.7.0 --activate
      - run: pnpm install --frozen-lockfile
      - run: pnpm dlx vercel build
